services:
  postgres-db:
    image: postgres:15
    container_name: notification-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notification_db
    ports:
      - "5432:5432"

  notification-service:
    build: .
    container_name: notification-app
    ports:
      - "8083:8083"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/notification_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123